package fonts

const regKeyWin = `SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`
const regKeyWow = `SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Fonts`

//goland:noinspection SpellCheckingInspection
const FontNamesWindows81 = `Aparajita Bold Italic(TrueType)
Batang & BatangChe & Gungsuh & GungsuhChe (TrueType)
Estrangelo Edessa (TrueType)
Euphemia (TrueType)
Gadugi (TrueType)
Gadugi Bold (TrueType)
Gautami (TrueType)
Gautami Bold (TrueType)
Gulim & GulimChe & Dotum & DotumChe (TrueType)
Iskoola Pota (TrueType)
Iskoola Pota Bold (TrueType)
Javanese Text (TrueType)
Kalinga (TrueType)
Kalinga Bold (TrueType)
Kartika (TrueType)
Kartika Bold (TrueType)
Khmer UI (TrueType)
Khmer UI Bold (TrueType)
Kokila Bold Italic(TrueType)
Lao UI (TrueType)
Lao UI Bold (TrueType)
Latha (TrueType)
Latha Bold (TrueType)
Leelawadee (TrueType)
Leelawadee Bold (TrueType)
Leelawadee UI (TrueType)
Leelawadee UI Bold (TrueType)
Leelawadee UI Semilight (TrueType)
MS Gothic & MS PGothic & MS UI Gothic (TrueType)
MS Mincho & MS PMincho (TrueType)
MV Boli (TrueType)
Malgun Gothic (TrueType)
Malgun Gothic Bold (TrueType)
Mangal (TrueType)
Mangal Bold (TrueType)
Meiryo & Meiryo Italic & Meiryo UI & Meiryo UI Italic (TrueType)
Meiryo Bold & Meiryo Bold Italic & Meiryo UI Bold & Meiryo UI Bold Italic (TrueType)
Microsoft Himalaya (TrueType)
Microsoft JhengHei (TrueType) & Microsoft JhengHei UI (TrueType)
Microsoft JhengHei Bold (TrueType) & Microsoft JhengHei UI Bold (TrueType)
Microsoft JhengHei Light (TrueType) & Microsoft JhengHei UI Light (TrueType)
Microsoft New Tai Lue (TrueType)
Microsoft New Tai Lue Bold (TrueType)
Microsoft PhagsPa (TrueType)
Microsoft PhagsPa Bold (TrueType)
Microsoft Tai Le (TrueType)
Microsoft Tai Le Bold (TrueType)
Microsoft YaHei (TrueType) & Microsoft YaHei UI (TrueType)
Microsoft YaHei Bold (TrueType) & Microsoft YaHei UI Bold (TrueType)
Microsoft YaHei Light (TrueType) & Microsoft YaHei UI Light (TrueType)
Microsoft Yi Baiti (TrueType)
MingLiU & PMingLiU & MingLiU_HKSCS (TrueType)
MingLiU-ExtB & PMingLiU-ExtB & MingLiU_HKSCS-ExtB (TrueType)
Mongolian Baiti (TrueType)
Myanmar Text (TrueType)
Myanmar Text Bold (TrueType)
Nirmala UI (TrueType)
Nirmala UI Bold (TrueType)
Nirmala UI Semilight (TrueType)
Nyala (TrueType)
Plantagenet Cherokee (TrueType)
Raavi (TrueType)
Raavi Bold (TrueType)
Shruti (TrueType)
Shruti Bold (TrueType)
SimSun & NSimSun (TrueType)
SimSun-ExtB (TrueType)
Sylfaen (TrueType)
Tunga (TrueType)
Tunga Bold (TrueType)
Urdu Typesetting Bold (TrueType)
Utsaah Bold Italic(TrueType)
Vrinda (TrueType)
Vrinda Bold (TrueType)
Yu Gothic (TrueType)
Yumin
Yumin Demibold
Yumin Light`